apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: estebanx64-dev-tls
spec:
  secretName: estebanx64-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: estebanx64.dev
  dnsNames:
    - estebanx64.dev
    - www.estebanx64.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - estebanx64.dev
          - www.estebanx64.dev
